name: spotify_clone_flutter
description: A simple Spotify clone to run on web and desktop.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  faker: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/screenshots/
  
  fonts:
    - family:  spotify
      fonts:
        - asset: assets/fonts/spotify.ttf
